platform :ios, '14.0' # אתה יכול לשנות ל-13 אם יש בעיות במפות

ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter build ios is executed first."
  end

  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting it and running flutter build ios again."
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper.rb'), flutter_root)

flutter_ios_podfile_setup

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  # Add your Flutter dependencies here
  pod 'supabase_flutter', '~> 2.8.4'
  pod 'http', '~> 0.13.6'
  pod 'url_launcher', '~> 6.1.5'
  pod 'google_maps_flutter', '~> 2.5.0'
  pod 'geolocator', '~> 13.0.4'
  pod 'flutter_polyline_points', '~> 1.0.0'
  pod 'font_awesome_flutter', '~> 10.8.0'
  pod 'google_fonts', '~> 4.0.4'
  pod 'shared_preferences', '~> 2.2.2'
  pod 'onesignal_flutter', '~> 5.3.0'
  pod 'flutter_dotenv', '~> 5.0.2'
  pod 'cupertino_icons', '~> 1.0.8'
  pod 'location', '~> 8.0.0'
  pod 'connectivity_plus', '~> 6.1.4'
  pod 'app_links', '~> 6.4.0'

  
end
